first_project/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns =[
    path("index",views.index,name="index"),
    path("register",views.register,name="register"),
    path("login",views.user_login,name="login"),
    path("logout",views.user_logout,name="logout"),
]

first_project/first_app/urls.py
from django.urls import path
from first_app import views


urlpatterns =[
    path("index",views.index,name="index"),
    path("forms",views.forms,name="forms"),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.urls import include
from basic_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/",views.index,name="index"),
    path("first_app/",include("first_app.urls")),
    path("basic_app/",include("basic_app.urls")),
]

first_project/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics",blank=True)

    def __str__(self):
        return  self.user.username

first_project/first_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class WebPage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name  = models.CharField(max_length=264,unique= True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name
    
class AccessReocrd(models.Model):
    name = models.ForeignKey(WebPage,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)
    

first_project/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User

        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo

        fields = ('portfolio_site','profile_pic')

first_project/first_app/forms.py
from typing import Any
from django import forms
from django.core import validators


class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter your email again:")
    text = forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data =  super().clean()
        email = all_clean_data["email"]
        vmail = all_clean_data["verify_email"]

        if email != vmail:
            raise forms.ValidationError("Make Sure both emails are same")

first_project/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm,UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout



# Create your views here.
def index(request):
    return render(request,"basic_app/index.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("basic_app:index"))


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]
            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,"basic_app/registration.html",{"user_form":user_form,"profile_form":profile_form,"registered":registered})


def user_login(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("basic_app:index"))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("User Not found")
            return HttpResponse("No account found")
    else:
        return render(request,"basic_app/login.html")

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic,WebPage,AccessReocrd
from first_app.forms import FormName

# Create your views here.

def index(request):
    wepages_list = AccessReocrd.objects.order_by("date")
    date_dict = {"acc_rec":wepages_list}
    return render(request,"first_app/index.html",context=date_dict)


def forms(request):
    form = FormName()
    if request.method == "POST":
        form = FormName(request.POST)

        if form.is_valid():
            print("Validation Success")
            print("Name" + form.cleaned_data["name"])
            print("Email"+form.cleaned_data["email"])
            print("Text"+form.cleaned_data["text"])
    return render(request,"forms/forms.html",{"form":form})

first_project/templates/basic_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Base</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">    
    </head>
    <body>
    <nav class="navbar">
        <div class="container">
            <ul class="nav navbar-bav">
                <li><a class="navbar-brand" href="{% url 'index'%}">DJANGO</a></li>
                <li><a class="navbar-item" href="{% url 'admin:index'%}">Admin</a></li>
                <li><a class="navbar-item" href="{% url 'basic_app:register'%}">register</a></li>
                {% if user.is_authenticated %}
                <li><a class="navbar-item" href="{% url 'basic_app:logout'%}">{{user.username}}</a></li>
                {%else%}
                <li><a class="navbar-item" href="{% url 'basic_app:login'%}">login</a></li>
                {%endif%}
            </ul>
        </div>
    </nav>
    {% block bodyblock %}
    {% endblock %}
    </body>
</html>

first_project/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block bodyblock %}
<h1>Welcome to index</h1>

{% endblock %}

first_project/templates/basic_app/login.html
{% extends "basic_app/base.html" %}

{%block bodyblock%}
<div class="jumbotron">
    <h1>Please Login</h1>

    <form action="{% url 'basic_app:login'%}" method="post">

        {%csrf_token%}
         <p>User Name</p>
         <input type="text" name="username" placeholder="Enter Username" />
         <p>Password</p>
         <input type="password" name="password" placeholder="" />
         <input type="submit" value="submit" />   
    </form>

</div>
{% endblock %}

first_project/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% block bodyblock %}

<div class="jumbotron">
    {% if registered %}
    <h2> Thank you for registered</h2>
    {%else%}
    <h2>Please register</h2>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Submit" />
    </form>
    {%endif%}
</div>
{% endblock %}

first_project/templates/first_app/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>First Page</title>
    </head>
    <body>
        <h1>Hello, This is index.html</h1>
        {% if acc_rec %}
        {% for i in acc_rec %}
            <p>{{ i.date }}</p>
            {% endfor %}
        {% endif %}
    </body>
</html>

first_project/templates/forms/forms.html
<!DOCTYPE html>
<html>
    <head>
        <title>Forms Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body>
        <h1>Hello, This is froms.html</h1>
        <div class="container">
        <form method="POST">
            {% csrf_token%}    
            {{form.as_p}}
            <input type="submit" value="SUBMIT" class="btn btn-primary">    
        </form>
    </div>
    </body>
</html>